"""add_refresh_token_and_expires_at_to_session

Revision ID: 04440cc21fd8
Revises: 475b5c37fba9
Create Date: 2025-07-12 20:46:06.265061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04440cc21fd8'
down_revision: Union[str, Sequence[str], None] = '475b5c37fba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('refresh_token', sa.Text(), nullable=False))
    op.add_column('session', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.create_index('ix_session_refresh_token', 'session', ['refresh_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_refresh_token', table_name='session')
    op.drop_column('session', 'expires_at')
    op.drop_column('session', 'refresh_token')
    # ### end Alembic commands ###
