"""add_verified_field_to_password_reset_token

Revision ID: ab2ae2603ce9
Revises: 04440cc21fd8
Create Date: 2025-07-14 15:46:58.192423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2ae2603ce9'
down_revision: Union[str, Sequence[str], None] = '04440cc21fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
