"""final changes

Revision ID: e3fa278d0291
Revises: ba7c221c7afe
Create Date: 2025-07-02 18:56:28.182847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3fa278d0291'
down_revision: Union[str, Sequence[str], None] = 'ba7c221c7afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('on_boarding', sa.Column('recovery_email', sa.String(), nullable=True))
    op.add_column('on_boarding', sa.Column('address', sa.String(), nullable=True))
    op.add_column('on_boarding', sa.Column('city', sa.String(), nullable=True))
    op.add_column('on_boarding', sa.Column('state', sa.String(), nullable=True))
    op.add_column('on_boarding', sa.Column('zip_code', sa.String(), nullable=True))
    op.add_column('on_boarding', sa.Column('country', sa.String(), nullable=True))
    op.add_column('on_boarding', sa.Column('linked_in', sa.String(), nullable=True))
    op.add_column('on_boarding', sa.Column('preferred_payment_method', sa.String(), nullable=True))
    op.add_column('on_boarding', sa.Column('preferred_theme', sa.String(), nullable=True))
    op.drop_column('on_boarding', 'socials')
    op.drop_column('on_boarding', 'preferences')
    op.drop_column('on_boarding', 'company')
    op.add_column('user', sa.Column('is_term_accepted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_term_accepted')
    op.add_column('on_boarding', sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('on_boarding', sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('on_boarding', sa.Column('socials', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('on_boarding', 'preferred_theme')
    op.drop_column('on_boarding', 'preferred_payment_method')
    op.drop_column('on_boarding', 'linked_in')
    op.drop_column('on_boarding', 'country')
    op.drop_column('on_boarding', 'zip_code')
    op.drop_column('on_boarding', 'state')
    op.drop_column('on_boarding', 'city')
    op.drop_column('on_boarding', 'address')
    op.drop_column('on_boarding', 'recovery_email')
    # ### end Alembic commands ###
